---
- name: Using Ansible to call Python code
  gather_facts: no
  hosts: localhost      # planetexpress

  tasks:
          - name: call my better python script
            script: ~/ans/scripts/parselog.py
            args:
              executable: python3

          - name: load my yaml file that was just created
            include_vars:
                    name: ips
                    file: ~/ans/files/parsed.ips

          - debug:
                  var: ips
