---
- name: Using Ansible to call Python code
  gather_facts: no
  hosts: localhost      # planetexpress

  tasks:
          - name: call my python script
            script: ~/ans/scripts/parselog.py
            args:
              executable: python3
            register: results

          - debug:
                  var: results
